### ISSUE TITLE
Visual C++ Code Analysis broken by commit 99c425a

### ISSUE THREAD

**Issue by rysavyjan** [microsoft/wil#105]
Microsoft Visual C++ 2019 version 16.3.3, following simple module:

```cpp
#include "wil/com.h"

int main() {}
```

Code Analysis works fine with f74a30b64a48a4df13f34fcd824a2f8c108b7748
```
1>------ Build started: Project: wil_analyze, Configuration: Debug Win32 ------
1>wil_analyze.cpp
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

but fails with 99c425a12c0e48da7e7b172c448827b34496c4a9 https://github.com/microsoft/wil/pull/80
```
1>------ Build started: Project: wil_analyze, Configuration: Debug Win32 ------
1>wil_analyze.cpp
1>E:\Source\wil_analyze\wil\include\wil\result_macros.h(3617,1): error C2059: syntax error: '<L_GRAMMAR_template_head_l>'
1>E:\Source\wil_analyze\wil\include\wil\result_macros.h(3618,1): error C2143: syntax error: missing ';' before '{'
1>E:\Source\wil_analyze\wil\include\wil\result_macros.h(3618,1): error C2447: '{': missing function header (old-style formal list?)
1>E:\Source\wil_analyze\wil\include\wil\result_macros.h(3626,1): error C2059: syntax error: ''template<''
1>E:\Source\wil_analyze\wil\include\wil\result_macros.h(3628,1): error C2143: syntax error: missing ';' before '{'
...
1>E:\Source\wil_analyze\wil\include\wil\result_macros.h(5301,31): error C2039: 'ReportFailure_NtStatus': is not a member of 'wil::details'
1>E:\Source\wil_analyze\wil\include\wil\result_macros.h(5301,53): fatal error C1003: error count exceeds 100; stopping compilation
1>Done building project "wil_analyze.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

I wondered why Code Analysis works fine in https://github.com/microsoft/terminal - but WIL is held back there on working version e8c599bca6c56c44b6730ad93f6abbc9ecd60fc1

**Comment by sylveon** [comment]
Minimum repro:
```cpp
#include <Windows.h>

enum FailureType {};

_Success_(true)
_Translates_Win32_to_HRESULT_(err)
template<FailureType T>
__declspec(noinline) inline HRESULT ReportFailure_Win32(DWORD err)
{
	return __HRESULT_FROM_WIN32(err);
}
```

**Comment by sylveon** [comment]
Moving the SAL annotations under the template head instead of above fixes it.

**Comment by jlaanstra** [comment]
I filed a developer community ticket for this a few weeks ago: https://developercommunity.visualstudio.com/content/problem/782482/-translates-win32-to-hresult-sal-annotation-is-bro.html I've posted a link to the PR there.
