### ISSUE TITLE
Staging.h fails to compile in VS 17.6.5 with error C2678

### ISSUE THREAD

**Issue by JuanMejiaVelez** [microsoft/wil#346]
When upgrading Visual Studio to 17.6.5 project fails to compile reporting an error in Staging.h

Error C2678 
binary '&=': no operator found which takes a left-hand operand of type 'FEATURE_ENABLED_STATE' (or there is no acceptable conversion)
\packages\Microsoft.Windows.Wil.Internal.0.2.131\inc\wil\Staging.h
Line: 7092

**Comment by mcooley** [comment]
This issue occurred with a version of wil that's not on GitHub, and it wasn't a bug in wil--it was an issue with attempting to export a wil type from a C++ module. This issue can be closed, since it's not applicable here.
